# Generated by Django 2.2.6 on 2019-10-14 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='imagecomment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_comments', to='main.Image'),
        ),
    ]
